name: Build and Test

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install ARM GCC toolchain
      run: sudo apt-get install -y gcc-arm-linux-gnueabihf cmake libcmocka-dev

    # Compile C program
    - name: Compile Tests
      run: |
        gcc main.c -o main 

    # Run C tests
    - name: Run C tests
      run: | 
      set -e
      
      if [ "$(./main)" == "235 128 128" ]; then 
        echo "Match" 
      else 
        echo "No match";
        exit 1
      fi