name: Build and Test C program for ARM

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install ARM GCC toolchain
      run: sudo apt-get install -y gcc-arm-linux-gnueabihf

    - name: Compile C program
      run: arm-linux-gnueabihf-gcc main.c -o main_arm

    - name: Run compiled program
      run: ./main_arm

    - name: Run tests
      run: |
        #!/bin/bash
        set -e
        
        # Test 1: Check if the program runs without errors
        if ./main_arm; then
          echo "Test 1: Program execution - PASSED"
        else
          echo "Test 1: Program execution - FAILED"
          exit 1
        fi
        
        # Test 2: Add more tests as needed
        #!/bin/bash
        set -e
        
        # Define input parameters
        input="\"RGB\" 255 255 255"
        
        # Define expected output
        expected_output="235 128 128"
        
        # Run the program with input parameters and capture the output
        output=$(echo $input | ./main_arm)
        
        # Check if the output matches the expected output
        if [ "$output" == "$expected_output" ]; then
          echo "Test: RGB conversion white - PASSED"
        else
          echo "Test: RGB conversion white - FAILED"
          echo "Expected output: $expected_output"
          echo "Actual output: $output"
          exit 1
        fi
        
        # Test 3
        #!/bin/bash
        set -e
        
        # Define input parameters
        input="\"RGB\" 123 32 213"
        
        # Define expected output
        expected_output="85 194 155"
        
        # Run the program with input parameters and capture the output
        output=$(echo $input | ./main_arm)
        
        # Check if the output matches the expected output
        if [ "$output" == "$expected_output" ]; then
          echo "Test: RGB conversion purple - PASSED"
        else
          echo "Test: RGB conversion purple - FAILED"
          echo "Expected output: $expected_output"
          echo "Actual output: $output"
          exit 1
        fi
